name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_single:
    # Single/simple build instructions to ensure e.g. that build deps for -py2
    # do not implicitly fix -py3 builds (which would fail alone then).
    name: 'test: ${{ matrix.m_name }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - m_name: vim71
            m_args: -tag v7.1 -name vim71 -prebuild_script 'echo "#define FEAT_PROFILE" >> src/feature.h'
          - m_name: vim73
            m_args: -tag v7.3.429 -name vim73 -py
          - m_name: vim74-trusty
            m_args: -tag v7.4.052 -name vim74-trusty -py3
          - m_name: vim-master
            m_args: -tag master -py2 -py3 -ruby -lua
          - m_name: neovim-v0.2.0
            m_args: -tag neovim:v0.2.0 -py2 -py3 -ruby
          - m_name: neovim-v0.5.0
            m_args: -tag neovim:v0.5.0 -py3
          - m_name: neovim-master
            m_args: -tag neovim:master -py2 -py3 -ruby
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build example for test
        run: |
          cat > example/Dockerfile.tests <<EOF
          FROM vim-testbed-base
          RUN install_vim ${{ matrix.m_args }} -build
          EOF
          make build_example_for_test
      - run: make -C example test_vims_basic_test

  test_full_example:
    name: Test full example
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make build_example_for_test
      - run: make --keep-going test_example
