name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_single:
    name: ${{ matrix.vim_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - vim_name: vim71
            install_vim_args: -name vim71 -prebuild_script 'echo "#define FEAT_PROFILE" >> src/feature.h'
          - vim_name: vim73
            install_vim_args: -tag v7.3.429 -name vim73 -py
          - vim_name: vim74-trusty
            install_vim_args: -tag v7.4.052 -name vim74-trusty -py3
          - vim_name: vim-master
            install_vim_args: -tag master -py2 -py3 -ruby -lua
          - vim_name: neovim-v0.2.0
            install_vim_args: -tag neovim:v0.2.0 -py2 -py3 -ruby
          - vim_name: neovim-v0.5.0
            install_vim_args: -tag neovim:v0.5.0 -py3
          - vim_name: neovim-master
            install_vim_args: -tag neovim:master -py2 -py3 -ruby
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build example for test
        run: |
          printf 'FROM vim-testbed-base\nRUN install_vim %s -build\n' '${{ matrix.install_vim_args }}' > example/Dockerfile.tests
          make build_example_for_test
      - run: make -C example test_vims_basic_test

  test_full:
    needs: test_single
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make build_example_for_test
      - run: make --keep-going test_example
